spring:
  application:
    name: FJDemo

app:
  #  事件上报
  events-report-url: https://23.210.52.92:30032/api/push/eventReport/v1
  #  自闭环事件上报
  close_loop_events-report-url: https://23.210.52.92:30032/api/push/selfEventReport/push
  #  自闭环事件处置信息上报
  close_loop_disposal_info_report_url: https://23.210.52.92:30032/api/push/selfTaskOrderResult/push

  #车间参数
  workshop-app-code: A50023600040664202412008847
  workshop-app-secret: zq0PLAEsqOhtKoisY+kVqCcYh1lY5Ztu4Qzqq0kpleUfJAfVsP+M2w==
  workshop-app-token: 0a51811816e840799dc29b528272e75f

  #  儿童参数
  children-app-code: A50023600042595202501009014
  children-app-secret: lYVljvFWquiy6XmM2gvCLbv5pFgegnP9Sne5pm/Q0ssfJAfVsP+M2w==

